### ISSUE TITLE
Using Lighthouse to test the current build instead of an absolute URL

### ISSUE THREAD

**Issue by Klynger** [netlify/netlify-plugin-lighthouse#425]
**Is your feature request related to a problem? Please describe.**

The Lighthouse plugin is executed in every build on Netlify. So it would make sense to have a way to test the current build instead of an absolute URL because what usually the user wants is to compare differences between both builds.

**Describe the solution you'd like**
I would like to have a way to pass something like

```toml
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins.inputs.audits]]
    path = "/"
  [[plugins.inputs.audits]]
    path = "/features"
  [[plugins.inputs.audits]]
    path = "/blog/what-is-new-in-our-products"
```
instead of passing absolute URLs

```toml
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    url = "https://mysite.com/"
  [[plugins.inputs.audits]]
    url = "https://mysite.com/features"
  [[plugins.inputs.audits]]
    url = "https://mysite.com/blog/what-is-new-in-our-products"
```

**Describe alternatives you've considered**
As I [described on Netlify Community](https://answers.netlify.com/t/how-to-pass-relative-path-to-lighthouse-plugin/70387), I tried to pass the relative path to the URL attribute, but it didn't work as expected. I tried to use `path` instead of `URL`, but it didn't work either.
