### ISSUE TITLE
Not working in CD builds

### ISSUE THREAD

**Issue by SteveALee** [netlify/netlify-plugin-lighthouse#495]
**Describe the bug**

As per the blog post I enabled the plugin for one of my sites and change the netlify.toml to run for desktop.

The result CD build showed the plugin was enabled but it's post build step is 9ms and there are no results in the feed and I cannot find any in the control panel (but I've not idea where to look.

It works locally - took some

**To Reproduce**

1. install plugin
2. configure toml locally
3. push changes

**Expected behavior**
A lighthous score in the build output and somewhere in the control panel

**Screenshots**
netlify.toml
```toml
[build]
# with debugging: command = "git submodule update --init --remote && bundle exec jekyll build --verbose --trace --config '_config.yml,_config_staging.yml'"
command = "git submodule update --init --remote && npm install && bundle exec jekyll build --trace --config '_config.yml,_config_staging.yml'"
publish = "_site"

[build.environment]
RUBY_VERSION = "2.6.2"

[[redirects]]
from = "/wai-website"
to = "/"
status = 404

[dev]
command = "bundle exec jekyll serve -w --livereload --config _config.yml,_config_staging.yml"

[functions]
directory = "_functions"
node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[plugins]]
# See https://github.com/netlify/netlify-plugin-lighthouse#readme
package = "@netlify/plugin-lighthouse"
[plugins.inputs.settings]
preset = "desktop" # default is mobile
locale = "en"
# to audit an HTML file other than index.html in a sub path of the build directory
#[[plugins.inputs.audits]]
#path = "pages/contact.html"

```

**Additional context**

partial build Log 

```
6:08:25 PM: ❯ Loading plugins
6:08:25 PM:    - @netlify/plugin-lighthouse@4.0.1 from netlify.toml and package.json
6:08:27 PM: ​
6:08:27 PM: ────────────────────────────────────────────────────────────────
6:08:27 PM:   1. @netlify/plugin-functions-install-core (onPreBuild event)  
6:08:27 PM: ────────────────────────────────────────────────────────────────
6:08:27 PM: ​
6:08:27 PM: ​
6:08:27 PM: (@netlify/plugin-functions-install-core onPreBuild completed in 10ms)



────────────────────────────────────────────────────────────────
6:10:03 PM:   4. @netlify/plugin-lighthouse (onPostBuild event)             
6:10:03 PM: ────────────────────────────────────────────────────────────────
6:10:03 PM: ​
6:10:03 PM: ​
6:10:03 PM: (@netlify/plugin-lighthouse onPostBuild completed in 9ms)
6:10:03 PM: ​
6:10:03 PM: ────────────────────────────────────────────────────────────────
6:10:03 PM:   5. Deploy site                                                
6:10:03 PM: ────────────────────────────────────────────────────────────────
6:10:03 PM: ​
```

**Comment by brittneypostma** [comment]
Does this plugin exist, I'm not seeing it in npm?
```toml
[[plugins]]
package = "@netlify/plugin-functions-install-core"
```
