### ISSUE TITLE
local build creates crazy directory

### ISSUE THREAD

**Issue by SteveALee** [netlify/netlify-plugin-lighthouse#496]
**Describe the bug**
I installed the plugin in control panel and then also for local dev.
It runs fine locally and I see the light house output in the terminal but it also creates a weird folder  "/home/wsl/wai/wai-website/C:\Users\steve\AppData\Local\lighthouse.41998921" which play havoc with git

**To Reproduce**
1. install the plugin with npm install
2. edit netlify toml;
```toml
[build]
# with debugging: command = "git submodule update --init --remote && bundle exec jekyll build --verbose --trace --config '_config.yml,_config_staging.yml'"
command = "git submodule update --init --remote && npm install && bundle exec jekyll build --trace --config '_config.yml,_config_staging.yml'"
publish = "_site"

[build.environment]
RUBY_VERSION = "2.6.2"

[[redirects]]
from = "/wai-website"
to = "/"
status = 404

[dev]
command = "bundle exec jekyll serve -w --livereload --config _config.yml,_config_staging.yml"

[functions]
directory = "_functions"
node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[plugins]]
# See https://github.com/netlify/netlify-plugin-lighthouse#readme
package = "@netlify/plugin-lighthouse"
[plugins.inputs.settings]
preset = "desktop" # default is mobile
locale = "en"
# to audit an HTML file other than index.html in a sub path of the build directory
#[[plugins.inputs.audits]]
#path = "pages/contact.html"

```
3. `ntl build`
4.  get the folder `C:\Users\steve\AppData\Local\lighthouse.41998921` in workspace
5. 
**Expected behavior**

No such windows path foldername  in workspace 

**Additional context**
Local dev  is vscode remote dev on windows 11 using WSL (Ubuntu)
