### ISSUE TITLE
"Summary for path '/': undefined"

### ISSUE THREAD

**Issue by spacedawwwg** [netlify/netlify-plugin-lighthouse#598]
**Describe the bug**
```
"Summary for path '/': undefined"
```
I have installed the plugin but unable to get it to work as the response is always the above

netlify.toml
```toml
[build]
command = "yarn build"
publish = "dist/"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../../core/ ../../sanity/ ../../utils/"

[build.environment]
# Match version in monorepo root .yarnrc.yml
YARN_VERSION = "3.6.3"
NETLIFY_USE_YARN = "true"
NETLIFY_YARN_WORKSPACES = "true"
YARN_ENABLE_GLOBAL_CACHE = "true"
YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"
CYPRESS_INSTALL_BINARY = "0"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NODE_ENV = "production"
NODE_VERSION = "18"

[dev]
port = 3000
publish = "dist"
autoLaunch = false
framework = "#custom"

[functions]
directory = "functions/"
```

**To Reproduce**
Install plugin via UI without any extra config

**Expected behavior**
Receive a lighthouse report

**Screenshots**
<img width="684" alt="image" src="https://github.com/netlify/netlify-plugin-lighthouse/assets/1691867/fe997066-0c3c-4a41-8a86-967fa1014718">
<img width="718" alt="image" src="https://github.com/netlify/netlify-plugin-lighthouse/assets/1691867/b5a1fef5-0cc1-468a-add9-d6c842f9c2d6">

**Comment by spacedawwwg** [comment]
Same result as above when running a build with a clean cache

**Comment by georgeadamson** [comment]
Also getting this same message in the build logs: "Summary for path '/': undefined"

**Comment by christopher-theagen** [comment]
Potentially same root-issue: https://github.com/netlify/netlify-plugin-lighthouse/issues/601

**Comment by christopher-theagen** [comment]
Also getting the "Summary for path '/': undefined" message for **non-cache-busted-builds**; cache-clear builds work as expected.

Have tried:
1) per [566](https://github.com/netlify/netlify-plugin-lighthouse/issues/566)
  i) `LIGHTHOUSE_RUN_ON_SUCCESS` as ENV VAR 
  ii) `[plugins.inputs] run_on_success = "true"` in `netlify.toml`
2) removing `@netlify/plugin-lighthouse` from `netlify.toml` and installing from Netlify UI
3) per [548](https://github.com/netlify/netlify-plugin-lighthouse/issues/548)
  i) specifying `NODE_VERSION="20"` in `netlify.toml`
  ii) have removed `yarn.lock` and regenerated, post upgrades (noted below)

Running into this after upgrading `node` (from `16.20.0`) & `next` (from `12.3.4`).

Relevant, currently engine/deps:
```
  "engines": {
    "node": "20.11.0"
  },
  "dependencies": {
    "next": "14.1.0",
    ...
  },
  "devDependencies": {
    "@netlify/plugin-lighthouse": "6.0.0",
    "@netlify/plugin-nextjs": "4.41.3",
    ...
  }
```

`netlify.toml`
```toml
[build]
  ignore = "bash ../../netlify-ignore.sh"
  base = "packages/uwhealth.org"
  command = "yarn build && yarn build:flex:clear"
  publish = "out"
  functions = "serverless"

[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.19"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[dev]
  command = "yarn workspace uw-health-org next dev"
  functions = "serverless"
  publish = "public"
  framework = "#custom"
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```
